server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

spring:
  application:
    name: service1

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: zipkin
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      probability: 1.0

